export async function mockGenerateScript(prompt: string): Promise<string> {
  await new Promise((resolve) => setTimeout(resolve, 700));

  const safePrompt = prompt.trim() || "将所有报文周期改为 20ms";

  return [
    "// Auto-generated by CANvas AI Script Copilot",
    "variables",
    "{",
    "  msTimer canTxTimer;",
    "}",
    "",
    "on start",
    "{",
    "  setTimer(canTxTimer, 20);",
    "}",
    "",
    "on timer canTxTimer",
    "{",
    "  // User intent:",
    `  // ${safePrompt}`,
    "  output(MOTOR_CTRL_0x1A2);",
    "  output(BMS_STATUS_0x180);",
    "  setTimer(canTxTimer, 20);",
    "}",
  ].join("\n");
}
